// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Heading: typeof import('./components/common/Heading.vue')['default']
    Rating: typeof import('./components/common/Rating.vue')['default']
    Restaurant: typeof import('./components/restaurant/Restaurant.vue')['default']
    RestaurantList: typeof import('./components/restaurant/RestaurantList.vue')['default']
    ReviewsList: typeof import('./components/restaurant/ReviewsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./components/common/Spinner.vue')['default']
    Text: typeof import('./components/common/Text.vue')['default']
  }
}
